name: deploy_production

on:
  push:
    branches:
      - release

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy Production
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.5
          channel: stable

      - name: Build Flutter App
        run: |
          flutter packages get
          flutter build web --target lib/main.dart --web-renderer canvaskit --release
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PINBALL_PROD }}"
          channelId: live
          projectId: io-pinball

      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PINBALL_PROD }}